<?php
namespace Animals;


class Duck extends Animal {

	public $duck_prop = "bird";

	public function make_noise() {
		return parent::make_noise(); // TODO: Change the autogenerated stub
	}

	public function iterateProps() {
		foreach ( $this as $key => $value ) {
			print "$key => $value<br/>";
		}
	}

}

